<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
  'title' => t('gdl2012 home'),
  'category' => t('Columns: 2'),
  'icon' => 'gdl2012-home.png',
  'theme' => 'gdl2012-home',
  'css' => 'gdl2012-home.css',
  'panels' => array(
    'left'        => t('Left side'),
    'right'       => t('Right side'),
    'sponsors'   => t('Sponsors'),
  ),
);
